spring.application.name=Gestion_Foyer
server.port=4000

spring.datasource.url=jdbc:mysql://localhost:3306/GestionFoyerDB?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show.sql=true
spring.jpa.hibernate.ddl-auto = update

